# Generated by Django 2.0.8 on 2022-06-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220603_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.TextField(default='testsad;lfjas;ljk')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default='default value'),
        ),
    ]
